# Generated by Django 4.1.7 on 2023-05-02 16:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_remove_user_user_id_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSendMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receiver_name', models.CharField(max_length=255)),
                ('Subject', models.CharField(max_length=255)),
                ('Message_content', models.CharField(max_length=1000)),
                ('Message_file', models.FileField(upload_to='Documents/')),
                ('date_sent', models.DateField(default=django.utils.timezone.now)),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentReceiveMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sender', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('Message_content', models.CharField(max_length=1000)),
                ('date_received', models.DateField(default=django.utils.timezone.now)),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.student')),
            ],
        ),
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplicationForm', models.FileField(upload_to='Documents/')),
                ('InternshipReport', models.FileField(upload_to='Documents/')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.student')),
            ],
        ),
    ]
