# Generated by Django 4.1.7 on 2023-05-03 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_coordinator_table'),
        ('StudentDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsendmessages',
            name='Coordinator_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login.coordinator'),
        ),
    ]
