# Generated by Django 4.1.7 on 2023-05-05 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_coordinator_table'),
        ('StudentDashboard', '0003_remove_studentsendmessages_coordinator_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coordinator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.coordinator')),
            ],
        ),
    ]
