# Generated by Django 4.1.7 on 2023-05-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0004_coordinators'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinators',
            name='FullName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
