# Generated by Django 4.1.7 on 2023-05-05 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0005_coordinators_fullname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordinators',
        ),
    ]
