# Generated by Django 4.1.7 on 2023-05-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0007_officialletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsendmessages',
            name='Receiver_name',
            field=models.CharField(max_length=255),
        ),
    ]
