# Generated by Django 4.1.7 on 2023-05-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0012_alter_studentsendmessages_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsendmessages',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
