# Generated by Django 4.1.7 on 2023-05-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0015_studentsendmessages_coordinator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsendmessages',
            old_name='Coordinator',
            new_name='Receiver',
        ),
    ]
