# Generated by Django 4.1.7 on 2023-05-10 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_coordinator_table'),
        ('StudentDashboard', '0016_rename_coordinator_studentsendmessages_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsendmessages',
            name='Sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.student'),
        ),
    ]
