# Generated by Django 4.1.7 on 2023-05-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_coordinator_table'),
        ('StudentDashboard', '0017_studentsendmessages_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsendmessages',
            name='Sender',
        ),
        migrations.AddField(
            model_name='studentsendmessages',
            name='Sender',
            field=models.ManyToManyField(related_name='Sender', to='login.student'),
        ),
    ]
