# Generated by Django 4.1.7 on 2023-05-10 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_rename_coordinator_student_coordinator'),
        ('StudentDashboard', '0018_remove_studentsendmessages_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsendmessages',
            name='Sender',
        ),
        migrations.AddField(
            model_name='studentsendmessages',
            name='Sender_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.student'),
        ),
    ]
