# Generated by Django 4.1.7 on 2023-05-10 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0019_remove_studentsendmessages_sender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsendmessages',
            old_name='Sender_id',
            new_name='Sender',
        ),
    ]
