# Generated by Django 4.1.7 on 2023-05-10 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_rename_coordinator_student_coordinator'),
        ('StudentDashboard', '0020_rename_sender_id_studentsendmessages_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialletter',
            name='CoordinatorName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.coordinator'),
        ),
        migrations.AlterField(
            model_name='officialletter',
            name='StudentName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.student'),
        ),
    ]
