# Generated by Django 4.1.7 on 2023-05-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0021_alter_officialletter_coordinatorname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officialletter',
            old_name='CoordinatorName',
            new_name='coordinator',
        ),
        migrations.RenameField(
            model_name='officialletter',
            old_name='StudentName',
            new_name='student',
        ),
        migrations.AddField(
            model_name='officialletter',
            name='NumOfIncompleteInternships',
            field=models.IntegerField(default=2),
        ),
    ]
