# Generated by Django 4.1.7 on 2023-05-10 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0022_rename_coordinatorname_officialletter_coordinator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officialletter',
            options={'verbose_name': 'OfficialLetter'},
        ),
        migrations.AlterModelTable(
            name='officialletter',
            table='studentdashboard_officialletter',
        ),
    ]
