# Generated by Django 4.1.7 on 2023-05-12 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_rename_coordinator_student_coordinator'),
        ('StudentDashboard', '0025_alter_officialletter_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.coordinator'),
        ),
    ]
