# Generated by Django 4.1.7 on 2023-05-12 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0026_files_coordinator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='student_id',
            new_name='student',
        ),
    ]
