# Generated by Django 4.1.7 on 2023-05-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0027_rename_student_id_files_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='InternshipReport',
            field=models.FileField(default='Nofile', upload_to='Documents/'),
        ),
    ]
