# Generated by Django 4.1.7 on 2023-05-12 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0028_alter_files_internshipreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='date_sent',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
