# Generated by Django 4.1.7 on 2023-05-12 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0030_alter_files_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officialletter',
            old_name='student',
            new_name='sender',
        ),
    ]
