# Generated by Django 4.1.7 on 2023-05-12 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0032_rename_student_files_sender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='coordinator',
            new_name='Receiver',
        ),
    ]
