# Generated by Django 4.1.7 on 2023-05-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0033_rename_coordinator_files_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='ApplicationForm',
            field=models.FileField(default='Nofile', upload_to='Documents/ApplicationForm/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='InternshipReport',
            field=models.FileField(default='Nofile', upload_to='Documents/Reports'),
        ),
    ]
