# Generated by Django 4.1.7 on 2023-05-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0037_alter_files_applicationform_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officialletter',
            old_name='coordinator',
            new_name='coordinator_id',
        ),
        migrations.RenameField(
            model_name='officialletter',
            old_name='student',
            new_name='student_id',
        ),
    ]
