# Generated by Django 4.1.7 on 2023-05-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0038_rename_coordinator_officialletter_coordinator_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officialletter',
            options={},
        ),
    ]
