# Generated by Django 4.1.7 on 2023-05-12 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0039_alter_officialletter_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officialletter',
            old_name='student_id',
            new_name='requestedfrom',
        ),
        migrations.RenameField(
            model_name='officialletter',
            old_name='coordinator_id',
            new_name='requestedto',
        ),
    ]
