# Generated by Django 4.1.7 on 2023-05-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0041_rename_requestedto_officialletter_coordinator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialletter',
            name='NumOfIncompleteInternships',
            field=models.IntegerField(null=True),
        ),
    ]
