# Generated by Django 4.1.7 on 2023-05-12 14:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_rename_coordinator_student_coordinator'),
        ('StudentDashboard', '0042_alter_officialletter_numofincompleteinternships'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialLet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=255)),
                ('NumOfincintern', models.IntegerField()),
                ('date_requested', models.DateField(default=django.utils.timezone.now)),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.coordinator')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.student')),
            ],
        ),
        migrations.DeleteModel(
            name='OfficialLetter',
        ),
    ]
