# Generated by Django 4.1.7 on 2023-05-15 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0043_officiallet_delete_officialletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InternshipReport', models.FileField(default='None', upload_to='Documents/Reports/')),
                ('name', models.CharField(default='My Internship Report', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='files',
            name='ApplicationForm',
        ),
        migrations.RemoveField(
            model_name='files',
            name='InternshipReport',
        ),
        migrations.AddField(
            model_name='files',
            name='ApplicationFormStatus',
            field=models.CharField(choices=[('A', 'Approved'), ('W', 'Waiting For Approval'), ('R', 'Rejected')], default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='files',
            name='SGKStatus',
            field=models.CharField(choices=[('W', 'Waiting For Approval'), ('p', 'Processing'), ('D', 'Done')], default='None', max_length=255),
        ),
        migrations.CreateModel(
            name='SGKDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InternshipReport', models.FileField(default='None', upload_to='Documents/SGK_DOC')),
                ('name', models.CharField(default='SGK Document', max_length=255)),
                ('SGKDocument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentDashboard.files')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplicationForm', models.FileField(default='None', upload_to='Documents/ApplicationForm')),
                ('name', models.CharField(default='My Application Form', max_length=255)),
                ('InternshipForm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentDashboard.files')),
            ],
        ),
    ]
