# Generated by Django 4.1.7 on 2023-05-15 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0044_internshipreport_remove_files_applicationform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipform',
            name='InternshipForm',
        ),
        migrations.RemoveField(
            model_name='sgkdocument',
            name='SGKDocument',
        ),
        migrations.AddField(
            model_name='files',
            name='InternshipForm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentDashboard.internshipform'),
        ),
        migrations.AddField(
            model_name='files',
            name='InternshipReport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentDashboard.internshipreport'),
        ),
        migrations.AddField(
            model_name='files',
            name='SGKDocument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentDashboard.sgkdocument'),
        ),
    ]
