# Generated by Django 4.1.7 on 2023-05-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0045_remove_internshipform_internshipform_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sgkdocument',
            old_name='InternshipReport',
            new_name='SGK_File',
        ),
        migrations.RemoveField(
            model_name='files',
            name='ApplicationFormStatus',
        ),
        migrations.RemoveField(
            model_name='files',
            name='SGKStatus',
        ),
        migrations.AddField(
            model_name='internshipform',
            name='Status',
            field=models.CharField(choices=[('A', 'Approved'), ('W', 'Waiting For Approval'), ('R', 'Rejected')], default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='sgkdocument',
            name='Status',
            field=models.CharField(choices=[('W', 'Waiting For Approval'), ('p', 'Processing'), ('D', 'Done')], default='None', max_length=255),
        ),
    ]
