# Generated by Django 4.1.7 on 2023-05-15 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0046_rename_internshipreport_sgkdocument_sgk_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='InternshipForm',
        ),
        migrations.RemoveField(
            model_name='files',
            name='InternshipReport',
        ),
        migrations.RemoveField(
            model_name='files',
            name='SGKDocument',
        ),
        migrations.AddField(
            model_name='internshipform',
            name='AppForm',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentDashboard.files'),
        ),
        migrations.AddField(
            model_name='internshipreport',
            name='Repfile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentDashboard.files'),
        ),
        migrations.AddField(
            model_name='sgkdocument',
            name='SGKfile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentDashboard.files'),
        ),
    ]
