# Generated by Django 4.1.7 on 2023-05-15 04:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_rename_coordinator_student_coordinator'),
        ('StudentDashboard', '0047_remove_files_internshipform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipform',
            name='AppForm',
        ),
        migrations.RemoveField(
            model_name='internshipreport',
            name='Repfile',
        ),
        migrations.RemoveField(
            model_name='sgkdocument',
            name='SGKfile',
        ),
        migrations.AddField(
            model_name='internshipform',
            name='Receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.coordinator'),
        ),
        migrations.AddField(
            model_name='internshipform',
            name='date_sent',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='internshipform',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.student'),
        ),
        migrations.AddField(
            model_name='internshipreport',
            name='Receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.coordinator'),
        ),
        migrations.AddField(
            model_name='internshipreport',
            name='date_sent',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='internshipreport',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.student'),
        ),
        migrations.AddField(
            model_name='sgkdocument',
            name='Receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.coordinator'),
        ),
        migrations.AddField(
            model_name='sgkdocument',
            name='date_sent',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sgkdocument',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.student'),
        ),
        migrations.DeleteModel(
            name='files',
        ),
    ]
