# Generated by Django 4.1.7 on 2023-05-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0048_remove_internshipform_appform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipform',
            name='Status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Waitng For Approval', 'Waiting For Approval'), ('Rejected', 'Rejected')], default='None', max_length=255),
        ),
    ]
