# Generated by Django 4.1.7 on 2023-05-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0051_opportunities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunities',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
