# Generated by Django 4.1.7 on 2023-05-16 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_rename_coordinator_student_coordinator'),
        ('StudentDashboard', '0052_alter_opportunities_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officiallet',
            name='id',
        ),
        migrations.AlterField(
            model_name='officiallet',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.student'),
        ),
    ]
