# Generated by Django 4.1.7 on 2023-05-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0053_remove_officiallet_id_alter_officiallet_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentreceivemessages',
            old_name='Student_id',
            new_name='Receiver',
        ),
    ]
