# Generated by Django 4.1.7 on 2023-05-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0054_rename_student_id_studentreceivemessages_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreceivemessages',
            name='Message_file',
            field=models.FileField(null=True, upload_to='Documents/'),
        ),
    ]
