# Generated by Django 4.1.7 on 2023-05-16 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_rename_coordinator_student_coordinator'),
        ('StudentDashboard', '0055_studentreceivemessages_message_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreceivemessages',
            name='Sender',
        ),
        migrations.AddField(
            model_name='studentreceivemessages',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.coordinator'),
        ),
    ]
