# Generated by Django 4.1.7 on 2023-05-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0058_generatedoffletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipform',
            name='Rejection_reason',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
