# Generated by Django 4.1.7 on 2023-05-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0059_internshipform_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='officiallet',
            name='pdf_file',
            field=models.FileField(default='None', upload_to='Documents/officialletter/'),
        ),
        migrations.DeleteModel(
            name='Generatedoffletter',
        ),
    ]
