# Generated by Django 4.1.7 on 2023-05-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0060_officiallet_pdf_file_delete_generatedoffletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunities',
            name='image',
        ),
    ]
