# Generated by Django 4.1.7 on 2023-05-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0062_alter_sgkdocument_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipform',
            name='SGK_File',
            field=models.FileField(default='None', upload_to='Documents/SGK_DOC'),
        ),
        migrations.AddField(
            model_name='internshipform',
            name='SGK_Status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Waitng For Approval', 'Waiting For Approval'), ('Rejected', 'Rejected')], default='Processing', max_length=255),
        ),
        migrations.AlterField(
            model_name='internshipform',
            name='name',
            field=models.CharField(default='SGK Document', max_length=255),
        ),
        migrations.DeleteModel(
            name='SGKDocument',
        ),
    ]
