# Generated by Django 4.1.7 on 2023-05-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0063_internshipform_sgk_file_internshipform_sgk_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipform',
            name='SGK_Status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Waitng For Approval', 'Waiting For Approval'), ('Rejected', 'Rejected'), ('Done', 'Done')], default='Processing', max_length=255),
        ),
        migrations.AlterField(
            model_name='internshipform',
            name='Status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Waitng For Approval', 'Waiting For Approval'), ('Rejected', 'Rejected'), ('Done', 'Done')], default='Waitng For Approval', max_length=255),
        ),
    ]
