# Generated by Django 4.1.7 on 2023-05-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0064_alter_internshipform_sgk_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipform',
            name='SGK_Status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Waitng For Approval', 'Waiting For Approval'), ('Rejected', 'Rejected'), ('Done', 'Done')], default='Waiting For Approval', max_length=255),
        ),
    ]
