# Generated by Django 4.1.7 on 2023-05-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0065_alter_internshipform_sgk_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipform',
            name='name',
            field=models.CharField(default='My Application Form', max_length=255),
        ),
    ]
