# Generated by Django 4.1.7 on 2023-05-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0067_alter_internshipform_sgk_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipform',
            name='SGK_File',
            field=models.FileField(default='None', upload_to='sgkDocuments'),
        ),
    ]
