# Generated by Django 4.1.7 on 2023-05-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0069_officiallet_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipform',
            name='ApplicationFormUpload',
            field=models.BooleanField(default=False),
        ),
    ]
