# Generated by Django 4.1.7 on 2023-05-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0070_internshipform_applicationformupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipform',
            name='Notification',
            field=models.CharField(default='No updates', max_length=255),
        ),
    ]
