# Generated by Django 4.1.7 on 2023-05-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0071_internshipform_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipform',
            name='SGKNotification',
            field=models.CharField(default='', max_length=255),
        ),
    ]
