# Generated by Django 4.1.7 on 2023-05-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0074_internshipreport_is_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipreport',
            name='InternshipReport2',
            field=models.FileField(default='None', upload_to='Documents/Reports/'),
        ),
        migrations.AddField(
            model_name='internshipreport',
            name='is_uploaded2',
            field=models.BooleanField(default=False),
        ),
    ]
