# Generated by Django 4.1.7 on 2023-05-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0076_internshipreport2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipform',
            name='SGKNotification',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
