# Generated by Django 4.1.7 on 2023-05-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0077_alter_internshipform_sgknotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='officiallet',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
