# Generated by Django 4.1.7 on 2023-05-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0078_officiallet_is_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipform',
            name='ApplicationForm',
            field=models.FileField(default='', upload_to='static/Files'),
        ),
        migrations.AlterField(
            model_name='internshipform',
            name='Rejection_reason',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='internshipform',
            name='SGK_File',
            field=models.FileField(default='', upload_to='sgkDocuments'),
        ),
    ]
