# Generated by Django 4.1.7 on 2023-05-31 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0079_alter_internshipform_applicationform_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternshipReport2',
        ),
    ]
