# Generated by Django 4.1.7 on 2023-05-10 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_coordinator_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.coordinator'),
        ),
    ]
