# Generated by Django 4.1.7 on 2023-05-10 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_student_coordinator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Coordinator',
            new_name='coordinator',
        ),
    ]
