# Generated by Django 4.1.7 on 2023-05-23 11:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0005_rename_coordinator_student_coordinator'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerCenterSendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('Message_content', models.CharField(max_length=1000)),
                ('Message_file', models.FileField(upload_to='Documents')),
                ('sent_date', models.DateField(default=django.utils.timezone.now)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.coordinator')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.careercenter')),
            ],
        ),
        migrations.CreateModel(
            name='CareerCenterReceiveMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('Message_content', models.CharField(max_length=1000)),
                ('Message_file', models.FileField(upload_to='Documents')),
                ('sent_date', models.DateField(default=django.utils.timezone.now)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.careercenter')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.coordinator')),
            ],
        ),
    ]
