# Generated by Django 4.1.7 on 2023-05-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoordinatorDashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careercentersendmessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='careercentersendmessage',
            name='sender',
        ),
        migrations.DeleteModel(
            name='CareerCenterReceiveMessage',
        ),
        migrations.DeleteModel(
            name='CareerCenterSendMessage',
        ),
    ]
